### ISSUE TITLE
Weird Glitch

### ISSUE THREAD

**Issue by BobtheBob123456** [knokko/custom-items-gradle#160] opened 2022-04-07 22:29 UTC
Hello,
So something weird happens when bedrock players try to craft or move items fr inventory to chests. The items go into a glitched state and float around.

Could this please be fixed?

Thanks

https://photos.app.goo.gl/bg2hS5ysHp6V7gup7
https://photos.app.goo.gl/sMMNSMqBCHoJi83M7

**Comment by knokko** [comment] 2022-04-08 14:52
I have never tested this plug-in on bedrock version (and I haven't played bedrock version in a long time...) I will try this plug-in on bedrock version after finishing Custom Items 10 and I will see if I get the same problem.

**Comment by BobtheBob123456** [comment] 2022-04-08 18:40
Thanks, also make sure to install Geyser MC, otherwise, it will not work.

**Comment by BobtheBob123456** [comment] 2022-04-08 18:46
By that I mean you won't be able to join the server.

**Comment by knokko** [comment] 2022-04-22 18:49
Today, I tried this myself. I was not able to reproduce the problem you are describing, but I did encounter all kinds of problems. I just wrote this version which fixes many of these problems for *vanilla items* and *non-stacking* custom items. Custom crafting recipes still don't seem to work properly though. Could you test if this version is better for you as well?
[ThisContainersCustomItems.jar.zip](https://github.com/knokko/custom-items-gradle/files/8543282/ThisContainersCustomItems.jar.zip)

**Comment by knokko** [comment] 2022-07-15 07:50
This is fixed in Custom Items 10.8

**Closed by knokko** 2022-07-15 07:50 UTC
Labels: Expected difficulty: hard
