### ISSUE TITLE
Bedrock conflict

### ISSUE THREAD

**Issue by Insidi0usAngel** [knokko/custom-items-gradle#184] opened 2022-07-05 14:29 UTC
I am using Geyser-spigot + Floodgate to allow bedrock users onto my server. It is normal for bedrock users to not be able to see custom textures/resource packs for Java server and use such items, however, having custom items plugin + knokko core on the server has caused a conflict with the bedrock player whereby the crafting table does not hold recipes, ie if you click on make an iron chestplate the iron ingots flash on and off and leave an empty crafting table, if you want to craft something complex like a sea lantern and don't know the recipe then the bedrock user cannot make the item as it changed the crafting table in such a way as they can only use it if they drag and drop individual items into crafting slots.  On disabling custom items plugin + knokko core the issue for bedrock players with crafting table was fixed.  I hope there can be a fix for this at a future point as your plugin was easy to use and offered a lot of creativity and potential.

I see this is already reported on bedrock issues, but to add a bit more detail - this issue occurs on all bedrock platforms - pc and mobile phone.

**Comment by knokko** [comment] 2022-07-05 18:30
What happens when you try this custom version of custom items?
https://github.com/knokko/custom-items-gradle/files/8543292/ThisContainsCustomItems.jar.zip
Does that solve (part of) the problem?

**Comment by Insidi0usAngel** [comment] 2022-07-05 22:35
Just added the above Jar you sent me and knokko core back to plugins and I
can confirm now this fixes all issues with the crafting table!!
Thank you so much, did not expect you to fix it so fast !

**Comment by knokko** [comment] 2022-07-06 06:32
I was quick because someone else reported the same behavior before: https://github.com/knokko/custom-items-gradle/issues/160
This time, I should not forget to include this fix in the regular versions.

**Comment by BobtheBob123456** [comment] 2022-07-08 02:29
I can confirm. This is is the same glitch that happened to me.

**Comment by Insidi0usAngel** [comment] 2022-07-08 18:31
All the same support has been excellent so I gave your plugin a 5 star
rating.  I have a new discovery though which has only just happened in the
last couple days and I think I know the reason why... I was trouble
shooting a number of bedrock compatibility issues on the same day -
basically my server was previously using the pebblehost auto-updating 1.19
jar (which did not conflict with your plugin at all) but this was the
culprit of a chests issue, on replacing the .jar with the most recent
official paper mc version which fixed a bedrock incompatibility  (paper
version 50 onwards now using #56) I started getting a new error warning
with your plugin - see attachment...  But this in itself seems to be a
non-problem - there are no error messages in console other than warning
about not using crazy enchantments etc, and after adding 2 custom items
onto my server today these items had full functionality - so other than
getting a message that the server jar file is not supported by knokko there
is no actual error - everything works and no console spam/no ram leaks/no
loss of functionality etc....  I have installed another 2 plugins (not yet
configured) which potentially could cause conflict but I doubt it as it
seems to reference specifically not liking my server version since i
updated the paper.jar.  I don't know if you are already aware of this issue
and so let me know if you want it posting as a bug for your to do list, as
its only cosmetic it should be low on your priority list.

Thanks for making such an amazing plugin, it is so much fun to make these
custom items and then see them in action !!!

**Comment by knokko** [comment] 2022-07-08 20:48
Which attachment? I don't think your message has any attachments.

**Comment by Insidi0usAngel** [comment] 2022-07-08 22:27
Attachment should show, it's on my sent message history, here is the
attachment again and if that does not work then try:
https://www.dropbox.com/s/j8al2pu8vwgjecb/ci-message.jpg?dl=0

**Comment by knokko** [comment] 2022-07-09 07:08
Install Custom Items 10.5 or later to get rid of that warning.

**Comment by knokko** [comment] 2022-07-15 07:50
This fix is included in Custom Items 10.8

**Closed by knokko** 2022-07-15 07:50 UTC
