### ISSUE TITLE
Item texture disappears

### ISSUE THREAD

**Issue by RomaGreat55** [knokko/custom-items-gradle#148] opened 2022-01-16 12:16 UTC
Hi!

When I break something with a textured item, the texture of the item is reset. How can this be fixed?
![2022-01-16_13 14 39](https://user-images.githubusercontent.com/73752164/149659506-685aaef0-4be5-4037-923b-85cae97daac1.png)
![2022-01-16_13 14 43](https://user-images.githubusercontent.com/73752164/149659508-7477b1d2-1f21-4dff-a05b-c742e483b600.png)

**Comment by knokko** [comment] 2022-01-16 12:45
I don't think I have seen this problem before. Could you check whether this is caused by another plug-in? (Retry it with only CustomItems and KnokkoCore.) If it still occurs, please tell me the minecraft version and give the .cisb file.

**Comment by knokko** [comment] 2022-01-25 13:00
I will close this until the original poster responds.

**Closed by knokko** 2022-01-25 13:00 UTC
